version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "5001:5001"
    depends_on:
      - db
    environment:
      - PGUSER=postgres
      - PGHOST=db
      - PGDATABASE=postgres
      - PGPASSWORD=mysecretpassword
      - PGPORT=5432
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
