const date = Date();

export const userData = [
   {
      id: 1,
      name: "Emily",
      chort: 10,
      date: date,
      dailyFeedBack: "",
      workShopRating: 0,
      guestLectureRating: 0,
      userFeelingRating: 0,
      bootcamperOfTheWeek: "",
   },
   {
      id: 2,
      name: "Elliot",
      chort: 8,
      date: date,
      dailyFeedBack: "",
      workShopRating: 0,
      guestLectureRating: 0,
      userFeelingRating: 0,
      bootcamperOfTheWeek: "",
   },
   {
      id: 3,
      name: "Michael",
      chort: 11,
      date: date,
      dailyFeedBack: "",
      workShopRating: 0,
      guestLectureRating: 0,
      userFeelingRating: 0,
      bootcamperOfTheWeek: "",
   },
   {
      id: 4,
      name: "Craig",
      chort: 8,
      date: date,
      dailyFeedBack: "",
      workShopRating: 0,
      guestLectureRating: 0,
      userFeelingRating: 0,
      bootcamperOfTheWeek: "",
   },
];
