export const userData = [
   {
      name: "Emily",
      chort: 10,
      date: "",
      dailyFeedBack: "",
      workShopRating: 3,
      guestLectureRating: 2,
      userFeelingRating: 3,
      bootcamperOfTheWeek: "",
   },
   {
      name: "Elliot",
      chort: 8,
      date: "",
      dailyFeedBack: "",
      workShopRating: 4,
      guestLectureRating: 5,
      userFeelingRating: 5,
      bootcamperOfTheWeek: "",
   },
   {
      name: "Michael",
      chort: 11,
      date: "",
      dailyFeedBack: "",
      workShopRating: 3,
      guestLectureRating: 1,
      userFeelingRating: 2,
      bootcamperOfTheWeek: "",
   },
   {
      name: "Craig",
      chort: 8,
      date: "",
      dailyFeedBack: "",
      workShopRating: 4,
      guestLectureRating:1,
      userFeelingRating: 3,
      bootcamperOfTheWeek: "",
   },
];
